services:
  ricing-star:
    build: .
    ports:
      - "80:80"
    environment:
      - BASE_URL=http://127.0.0.1
      - TIMEOUT=10
      - EXTENSION_PATH=/srv/bot/ext.zip
      - FLAG=space{s0_much_leg4cy_0ut_there_4nyw4y_h0w_d0_y0u_c4ll_th4t??_ucssi??}
    restart: unless-stopped